extensions/tax/avalara/objects/HTTP_Service__mdt/HTTP_Service__mdt.object-meta.xml
<CustomObject>
    <label>HTTP Service</label>
    <pluralLabel>HTTP Services</pluralLabel>
</CustomObject>

extensions/tax/avalara/objects/HTTP_Service__mdt/fields/End_Point__c.field-meta.xml
<CustomField>
    <fullName>End_Point__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/HTTP_Service__mdt/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/tax/avalara/objects/HTTP_Service__mdt/fields/Mocked_Response__c.field-meta.xml
<CustomField>
    <fullName>Mocked_Response__c</fullName>
    <label>Mocked Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

extensions/tax/vertex/objects/HTTP_Service__mdt/fields/Named_Credentials__c.field-meta.xml
<CustomField>
    <fullName>Named_Credentials__c</fullName>
    <label>Named Credentials</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/HTTP_Service__mdt/fields/Service_Mode__c.field-meta.xml
<CustomField>
    <fullName>Service_Mode__c</fullName>
    <label>Service Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
                <default>true</default>
                <label>Live</label>
            </value>
            <value>
                <fullName>Mocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/shipping/FedEx Shipping/objects/HTTP_Service__mdt/fields/Service_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Service_Timeout__c</fullName>
    <label>Service Timeout</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Shipping_Provider__mdt/Shipping_Provider__mdt.object-meta.xml
<CustomObject>
    <label>Shipping Provider</label>
    <pluralLabel>Shipping Providers</pluralLabel>
</CustomObject>

extensions/shipping/UPS Shipping/objects/Shipping_Provider__mdt/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Shipping_Provider__mdt/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Shipping_Provider__mdt/fields/Context_Locale__c.field-meta.xml
<CustomField>
    <fullName>Context_Locale__c</fullName>
    <label>Context Locale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Shipping_Provider__mdt/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <label>Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Shipping_Provider__mdt/fields/Max_Weight_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Max_Weight_Threshold__c</fullName>
    <label>Max Weight Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Shipping_Provider__mdt/fields/Min_Weight_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Min_Weight_Threshold__c</fullName>
    <label>Min Weight Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Shipping_Provider__mdt/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>Used to store request template for a shipping request</description>
    <label>Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Shipping_Provider__mdt/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>HTTP_Service__mdt</referenceTo>
    <relationshipLabel>Integrations</relationshipLabel>
    <relationshipName>Integrations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Shipping_Provider__mdt/fields/Shipping_Options__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Options__c</fullName>
    <label>Shipping Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

extensions/shipping/UPS Shipping/classes/ShippingDetails.cls
public with sharing class ShippingDetails {
  private static Map<String, List<ShippingMetaData>> shippingProviders = new Map<String, List<ShippingMetaData>>();
  private static List<Shipping_Provider__mdt> shippingProviderMDTs;
  private ShippingDetails() {
  }

  public static List<ShippingMetaData> getMetaDataDTO(String contextId) {
    List<ShippingMetaData> shippingMetaDataDTOs = new List<ShippingMetaData>();
    String currentLocale = UserInfo.getLocale();
    String dataKey = contextId + '-' + currentLocale;
    if (shippingProviders.containsKey(dataKey)) {
      shippingMetaDataDTOs = shippingProviders.get(dataKey);
    } else {
      String webStoreName = [
        SELECT Name
        FROM WebStore
        WHERE Id = :contextId
        LIMIT 1
      ]
      .Name;
      shippingProviderMDTs = [
        SELECT
          Id,
          Impl_Class__c,
          Max_Weight_Threshold__c,
          Min_Weight_Threshold__c,
          QualifiedApiName,
          Request__c,
          Account_Number__c,
          Display_Order__c,
          Service__c,
          Shipping_Options__c,
          Carrier__c,
          Service__r.End_Point__c,
          Service__r.HTTP_Method__c,
          Service__r.Mocked_Response__c,
          Service__r.Service_Mode__c,
          Service__r.Service_Timeout__c,
          Service__r.Impl_Class__c,
          Service__r.Named_Credentials__c
        FROM Shipping_Provider__mdt
        WHERE
          Context_Name__c = :webStoreName
          AND Context_Locale__c = :currentLocale AND Is_Active__c = true 
        ORDER BY Display_Order__c ASC NULLS LAST
      ];
      if (shippingProviderMDTs != null && shippingProviderMDTs.size() > 0) {
        ShippingMetaData shippingMetaDataDTO;
        for (
          Shipping_Provider__mdt shippingProviderMDT : shippingProviderMDTs
        ) {
          shippingMetaDataDTO = new ShippingMetaData();
          shippingMetaDataDTO.id = shippingProviderMDT.id;
          shippingMetaDataDTO.requestJSON = shippingProviderMDT.Request__c;
          shippingMetaDataDTO.providerImplClass = shippingProviderMDT.Impl_Class__c;
          shippingMetaDataDTO.maxPackageWeight = shippingProviderMDT.Max_Weight_Threshold__c;
          shippingMetaDataDTO.minPackageWeight = shippingProviderMDT.Min_Weight_Threshold__c;
          shippingMetaDataDTO.shippinggMethodNames = shippingProviderMDT.Shipping_Options__c;
          shippingMetaDataDTO.accountNumber = shippingProviderMDT.Account_Number__c;
          shippingMetaDataDTO.displayOrder = Integer.valueOf(
            shippingProviderMDT.Display_Order__c
          );
          shippingMetaDataDTO.carrier = shippingProviderMDT.Carrier__c;
          shippingMetaDataDTO.endPoint = shippingProviderMDT.Service__r.End_Point__c;
          shippingMetaDataDTO.httpMethod = shippingProviderMDT.Service__r.HTTP_Method__c;
          shippingMetaDataDTO.mockedResponse = shippingProviderMDT.Service__r.Mocked_Response__c;
          shippingMetaDataDTO.serviceMode = shippingProviderMDT.Service__r.Service_Mode__c;
          shippingMetaDataDTO.serviceTimeout = shippingProviderMDT.Service__r.Service_Timeout__c;
          shippingMetaDataDTO.serviceImplClass = shippingProviderMDT.Service__r.Impl_Class__c;
          shippingMetaDataDTO.namedCredentials = shippingProviderMDT.Service__r.Named_Credentials__c;
          shippingMetaDataDTOs.add(shippingMetaDataDTO);
        }
        shippingProviders.put(dataKey, shippingMetaDataDTOs);
      }
    }
    return shippingMetaDataDTOs;
  }

  public static List<Shipping_Provider__mdt> getMetaDataObject() {
    return shippingProviderMDTs;
  }
}