extensions/tax/avalara/objects/HTTP_Service__mdt/HTTP_Service__mdt.object-meta.xml
<CustomObject>
    <label>HTTP Service</label>
    <pluralLabel>HTTP Services</pluralLabel>
</CustomObject>

extensions/tax/avalara/objects/HTTP_Service__mdt/fields/End_Point__c.field-meta.xml
<CustomField>
    <fullName>End_Point__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/HTTP_Service__mdt/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/tax/avalara/objects/HTTP_Service__mdt/fields/Mocked_Response__c.field-meta.xml
<CustomField>
    <fullName>Mocked_Response__c</fullName>
    <label>Mocked Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

extensions/tax/vertex/objects/HTTP_Service__mdt/fields/Named_Credentials__c.field-meta.xml
<CustomField>
    <fullName>Named_Credentials__c</fullName>
    <label>Named Credentials</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/HTTP_Service__mdt/fields/Service_Mode__c.field-meta.xml
<CustomField>
    <fullName>Service_Mode__c</fullName>
    <label>Service Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
                <default>true</default>
                <label>Live</label>
            </value>
            <value>
                <fullName>Mocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/shipping/FedEx Shipping/objects/HTTP_Service__mdt/fields/Service_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Service_Timeout__c</fullName>
    <label>Service Timeout</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/Tax_Provider__mdt.object-meta.xml
<CustomObject>
    <label>Tax Provider</label>
    <pluralLabel>Tax Providers</pluralLabel>
</CustomObject>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <label>Address Line1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Address_Line2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line2__c</fullName>
    <label>Address Line2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Commit__c.field-meta.xml
<CustomField>
    <fullName>Commit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Commit?</label>
    <type>Checkbox</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Consider_product_tax_codes__c.field-meta.xml
<CustomField>
    <fullName>Consider_product_tax_codes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates whether sending product tax code to the tax provider service or not. If it is set to true make sure every product has a tax code configured otherwise default product tax code will be used.</description>
    <inlineHelpText>This flag indicates whether sending product tax code to the tax provider service or not. If it is set to true make sure every product has a tax code configured otherwise default product tax code will be used.</inlineHelpText>
    <label>Consider product tax codes?</label>
    <type>Checkbox</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Context_Name__c.field-meta.xml
<CustomField>
    <fullName>Context_Name__c</fullName>
    <label>Context Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Customer_Tax_Exemption__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tax_Exemption__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates whether there can be customers who are eligible for tax exemption, if yes then customer needs to provide exemption code &amp; entity use code.</description>
    <label>Customer Tax Exemption?</label>
    <type>Checkbox</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Default_Product_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Default_Product_Tax_Code__c</fullName>
    <description>This field stores default product tax code and it is used when tax codes are sent to a tax calculator provider but a product doesn&apos;t have any  tax code configured.</description>
    <inlineHelpText>This field stores default product tax code and it is used when tax codes are sent to a tax calculator provider but a product doesn&apos;t have any  tax code configured.</inlineHelpText>
    <label>Default Product Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Default_Shipping_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Default_Shipping_Tax_Code__c</fullName>
    <label>Default Shipping Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SalesOrder</fullName>
                <default>true</default>
                <label>Avalara - SalesOrder</label>
            </value>
            <value>
                <fullName>SalesInvoice</fullName>
                <label>Avalara - SalesInvoice</label>
            </value>
            <value>
                <fullName>PurchaseOrder</fullName>
                <label>Avalara - PurchaseOrder</label>
            </value>
            <value>
                <fullName>PurchaseInvoice</fullName>
                <label>Avalara - PurchaseInvoice</label>
            </value>
            <value>
                <fullName>Avalara - ReturnOrder</fullName>
            </value>
            <value>
                <fullName>Avalara - ReturnInvoice</fullName>
            </value>
            <value>
                <fullName>InventoryTransferOrder</fullName>
                <label>Avalara - InventoryTransferOrder</label>
            </value>
            <value>
                <fullName>InventoryTransferInvoice</fullName>
                <label>Avalara - InventoryTransferInvoice</label>
            </value>
            <value>
                <fullName>QUOTATION</fullName>
                <label>Vertex - Quotation</label>
            </value>
            <value>
                <fullName>INVOICE</fullName>
                <label>Vertex - Invoice</label>
            </value>
            <value>
                <fullName>DISTRIBUTE_TAX</fullName>
                <label>Vertex - Distribute Tax</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Impl_Class__c.field-meta.xml
<CustomField>
    <fullName>Impl_Class__c</fullName>
    <label>Impl Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Product_Tax_Exemption__c.field-meta.xml
<CustomField>
    <fullName>Product_Tax_Exemption__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates whether there can be product(s) which are tax exempted</description>
    <label>Product Tax Exemption?</label>
    <type>Checkbox</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Request_Template__c.field-meta.xml
<CustomField>
    <fullName>Request_Template__c</fullName>
    <label>Request Template</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Tax_Provider__mdt/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>HTTP_Service__mdt</referenceTo>
    <relationshipLabel>Tax Providers</relationshipLabel>
    <relationshipName>Tax_Providers</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Shipping_Items_Taxable__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Items_Taxable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipping Items Taxable?</label>
    <type>Checkbox</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Taxation_Policy__c.field-meta.xml
<CustomField>
    <fullName>Taxation_Policy__c</fullName>
    <label>Taxation Policy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net</fullName>
                <default>true</default>
                <label>Net</label>
            </value>
            <value>
                <fullName>Gross</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CreateTransaction</fullName>
                <default>true</default>
                <label>Avalara - CreateTransaction</label>
            </value>
            <value>
                <fullName>AdjustTransaction</fullName>
                <label>Avalara - AdjustTransaction</label>
            </value>
            <value>
                <fullName>CommitTransaction</fullName>
                <label>Avalara - CommitTransaction</label>
            </value>
            <value>
                <fullName>RefundTransaction</fullName>
                <label>Avalara - RefundTransaction</label>
            </value>
            <value>
                <fullName>SALE</fullName>
                <label>Vertex - Sale</label>
            </value>
            <value>
                <fullName>Rental</fullName>
                <label>Vertex - Rental</label>
            </value>
            <value>
                <fullName>Lease</fullName>
                <label>Vertex - Lease</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/WebStore/fields/Tax_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Document_Type__c</fullName>
    <label>Tax Document Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/WebStore/fields/Tax_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Transaction_Type__c</fullName>
    <label>Tax Transaction Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/classes/TaxConfiguration.cls
public with sharing class TaxConfiguration {
  private static Map<String, TaxMetaData> taxProviders = new Map<String, TaxMetaData>();
  private static Tax_Provider__mdt taxProviderMDT;
  private TaxConfiguration() {
  }

  public static TaxMetaData getMetaDataDTO(String contextId, String transactionType,String docType) {
    TaxMetaData taxMetaDataDTO;
    String currentLocale = UserInfo.getLocale();
    String dataKey = contextId + '-' + currentLocale;
    if (taxProviders.containsKey(dataKey)) {
      taxMetaDataDTO = taxProviders.get(dataKey);
    } else {
      WebStore webStore = [
        SELECT Name,Tax_Document_Type__c,Tax_Transaction_Type__c
        FROM WebStore
        WHERE Id = :contextId
        LIMIT 1
      ];
      if(String.isBlank(transactionType)){
        transactionType = webStore.Tax_Transaction_Type__c;
      }
      if(String.isBlank(docType)){
        docType = webStore.Tax_Document_Type__c;
      }
      taxProviderMDT = [
        SELECT
          Id,
          QualifiedApiName,
          Taxation_Policy__c,
          Customer_Code__c,
          Company_Code__c,
          Shipping_Items_Taxable__c,
          Default_Shipping_Tax_Code__c,
          Default_Product_Tax_Code__c,
          Consider_product_tax_codes__c,
          Product_Tax_Exemption__c,
          Customer_Tax_Exemption__c,
          Document_Type__c,
          Transaction_Type__c,
          Commit__c,
          Address_Line1__c,
          Address_Line2__c,
          City__c,
          State__c,
          Zip_Code__c,
          Country_Code__c,
          Impl_Class__c,
          Request_Template__c,
          Service__r.End_Point__c,
          Service__r.HTTP_Method__c,
          Service__r.Mocked_Response__c,
          Service__r.Service_Mode__c,
          Service__r.Service_Timeout__c,
          Service__r.Impl_Class__c,
          Service__r.Named_Credentials__c
        FROM Tax_Provider__mdt
        WHERE
          Context_Name__c = :webStore.Name
          AND Context_Locale__c = :currentLocale
          AND Transaction_Type__c = :transactionType
          AND Document_Type__c = :docType
        LIMIT 1
      ];
      if (taxProviderMDT != null) {
        taxMetaDataDTO = new TaxMetaData();
        taxMetaDataDTO.requestJSON = taxProviderMDT.Request_Template__c;
        taxMetaDataDTO.providerImplClass = taxProviderMDT.Impl_Class__c;
        taxMetaDataDTO.companyCode = taxProviderMDT.Company_Code__c;
        taxMetaDataDTO.customerCode = taxProviderMDT.Customer_Code__c;
        taxMetaDataDTO.shipFromLine1 = taxProviderMDT.Address_Line1__c;
        taxMetaDataDTO.shipFromLine2 = taxProviderMDT.Address_Line2__c;
        taxMetaDataDTO.shipFromCity = taxProviderMDT.City__c;
        taxMetaDataDTO.shipFromState = taxProviderMDT.State__c;
        taxMetaDataDTO.shipFromCountry = taxProviderMDT.Country_Code__c;
        taxMetaDataDTO.shipFromZipCode = taxProviderMDT.Zip_Code__c;
        taxMetaDataDTO.defaultShippingTaxCode = taxProviderMDT.Default_Shipping_Tax_Code__c;
        taxMetaDataDTO.taxationPolicy = taxProviderMDT.Taxation_Policy__c;
        taxMetaDataDTO.shippingItemsTaxable = taxProviderMDT.Shipping_Items_Taxable__c;
        taxMetaDataDTO.defaultProductTaxCode = taxProviderMDT.Default_Product_Tax_Code__c;
        taxMetaDataDTO.useProductTaxCodes = taxProviderMDT.Consider_product_tax_codes__c;
        taxMetaDataDTO.productTaxExemption = taxProviderMDT.Product_Tax_Exemption__c;
        taxMetaDataDTO.customerTaxExemption = taxProviderMDT.Customer_Tax_Exemption__c;
        taxMetaDataDTO.transactionType = taxProviderMDT.Transaction_Type__c;
        taxMetaDataDTO.documentType = taxProviderMDT.Document_Type__c;
        taxMetaDataDTO.isCommit = taxProviderMDT.Commit__c;
        taxMetaDataDTO.endPoint = taxProviderMDT.Service__r.End_Point__c;
        taxMetaDataDTO.httpMethod = taxProviderMDT.Service__r.HTTP_Method__c;
        taxMetaDataDTO.mockedResponse = taxProviderMDT.Service__r.Mocked_Response__c;
        taxMetaDataDTO.serviceMode = taxProviderMDT.Service__r.Service_Mode__c;
        taxMetaDataDTO.serviceTimeout = taxProviderMDT.Service__r.Service_Timeout__c;
        taxMetaDataDTO.serviceImplClass = taxProviderMDT.Service__r.Impl_Class__c;
        taxMetaDataDTO.namedCredentials = taxProviderMDT.Service__r.Named_Credentials__c;
        taxProviders.put(dataKey, taxMetaDataDTO);
      }
    }
    return taxMetaDataDTO;
  }

  public static Tax_Provider__mdt getMetaDataObject() {
    return taxProviderMDT;
  }
}