common/objects/StoreCountryCode__c/StoreCountryCode__c.object-meta.xml
<CustomObject>
    <description>Valid Country Codes for a particular webstore</description>
    <label>Store Country Code</label>
    <nameField>
        <displayFormat>SCC-{000000}</displayFormat>
        <label>StoreCountryCode Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Country Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/objects/StoreCountryCode__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/objects/StoreCountryCode__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

common/objects/StoreCountryCode__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>WebStore</referenceTo>
    <relationshipLabel>Store Country Codes</relationshipLabel>
    <relationshipName>Store_Country_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

common/objects/StoreStateCode__c/StoreStateCode__c.object-meta.xml
<CustomObject>
    <description>Valid state codes for a country code and webstore</description>
    <label>Store State Code</label>
    <nameField>
        <displayFormat>SSC-{0000000}</displayFormat>
        <label>StoreStateCode Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store State Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/objects/StoreStateCode__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

common/objects/StoreStateCode__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

common/objects/StoreStateCode__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>WebStore</referenceTo>
    <relationshipLabel>Store State Codes</relationshipLabel>
    <relationshipName>Store_State_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

common/objects/StoreStateCode__c/fields/Store_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Store_Country_Code__c</fullName>
    <label>Store Country Code</label>
    <referenceTo>StoreCountryCode__c</referenceTo>
    <relationshipLabel>Store State Codes</relationshipLabel>
    <relationshipName>Store_State_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

common/classes/StoreCountryStateCodes.cls
public with sharing class StoreCountryStateCodes {

    @AuraEnabled(cacheable=true)
    public static Map<String, List<AddressOption>> getValidStateCodesByCode(Id storeId) {
        try {
            List<StoreStateCode__c> codeRecs = [SELECT Id, State__c, State_Code__c, Store_Country_Code__r.Country_Code__c FROM StoreStateCode__c  WHERE Store__c = :storeId WITH SECURITY_ENFORCED];

            // A map to hold country codes and their list of regions
            Map<String, List<AddressOption>> countryStatesMap = new Map<String, List<AddressOption>>();


            for (StoreStateCode__c record : codeRecs) {

                // Retrieve the country code from the relationship field
                String countryCode = record.Store_Country_Code__r.Country_Code__c;

                // Create a new State object for the current record
                AddressOption currentRegion = new AddressOption(record.State__c, record.State_Code__c, record.Id);

                // Check if the map already contains the country code key
                if (!countryStatesMap.containsKey(countryCode)) {
                    // If not, create a new list for this country code
                    countryStatesMap.put(countryCode, new List<AddressOption>());
                }
                // Add the state to the corresponding country's list
                countryStatesMap.get(countryCode).add(currentRegion);
            }

            return countryStatesMap;


        } catch ( Exception error) {
            System.debug('Error retrieving state codes for store: ' +error.getMessage());
            return null;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<AddressOption> getValidCountryCodes(Id storeId) {
        try {
            List<StoreCountryCode__c> codeRecs = [SELECT Country__c, Country_Code__c, Id FROM StoreCountryCode__c  WHERE Store__c = :storeId WITH SECURITY_ENFORCED];

            List<AddressOption> codes = new List<AddressOption>();

            for (StoreCountryCode__c codeRec : codeRecs) {
                System.debug('codeRec.Country__c: '+codeRec.Country__c+', codeRec.Country_Code__c: '+codeRec.Country_Code__c+', codeRec.Id: '+CodeRec.Id);
                AddressOption cc = new AddressOption(codeRec.Country__c, codeRec.Country_Code__c, codeRec.Id);
                System.debug('cc.label: '+cc.label+', : cc.value'+cc.value+', cc.id: '+cc.id);
                codes.add(cc);
            }
            System.debug('codes: '+codes.toString());
            System.debug('number of CountryCodes returned: '+codes.size());

            return codes;
        } catch ( Exception error) {
            System.debug('Error retrieving country codes for store: ' +error.getMessage());
            return null;
        }
    }
}