extensions/tax/avalara/objects/Tax_Provider__mdt/Tax_Provider__mdt.object-meta.xml
<CustomObject>
    <label>Tax Provider</label>
    <pluralLabel>Tax Providers</pluralLabel>
</CustomObject>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <label>Address Line1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Address_Line2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line2__c</fullName>
    <label>Address Line2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Commit__c.field-meta.xml
<CustomField>
    <fullName>Commit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Commit?</label>
    <type>Checkbox</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Consider_product_tax_codes__c.field-meta.xml
<CustomField>
    <fullName>Consider_product_tax_codes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates whether sending product tax code to the tax provider service or not. If it is set to true make sure every product has a tax code configured otherwise default product tax code will be used.</description>
    <inlineHelpText>This flag indicates whether sending product tax code to the tax provider service or not. If it is set to true make sure every product has a tax code configured otherwise default product tax code will be used.</inlineHelpText>
    <label>Consider product tax codes?</label>
    <type>Checkbox</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Context_Name__c.field-meta.xml
<CustomField>
    <fullName>Context_Name__c</fullName>
    <label>Context Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Customer_Tax_Exemption__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tax_Exemption__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates whether there can be customers who are eligible for tax exemption, if yes then customer needs to provide exemption code &amp; entity use code.</description>
    <label>Customer Tax Exemption?</label>
    <type>Checkbox</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Default_Product_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Default_Product_Tax_Code__c</fullName>
    <description>This field stores default product tax code and it is used when tax codes are sent to a tax calculator provider but a product doesn&apos;t have any  tax code configured.</description>
    <inlineHelpText>This field stores default product tax code and it is used when tax codes are sent to a tax calculator provider but a product doesn&apos;t have any  tax code configured.</inlineHelpText>
    <label>Default Product Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Default_Shipping_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Default_Shipping_Tax_Code__c</fullName>
    <label>Default Shipping Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SalesOrder</fullName>
                <default>true</default>
                <label>Avalara - SalesOrder</label>
            </value>
            <value>
                <fullName>SalesInvoice</fullName>
                <label>Avalara - SalesInvoice</label>
            </value>
            <value>
                <fullName>PurchaseOrder</fullName>
                <label>Avalara - PurchaseOrder</label>
            </value>
            <value>
                <fullName>PurchaseInvoice</fullName>
                <label>Avalara - PurchaseInvoice</label>
            </value>
            <value>
                <fullName>Avalara - ReturnOrder</fullName>
            </value>
            <value>
                <fullName>Avalara - ReturnInvoice</fullName>
            </value>
            <value>
                <fullName>InventoryTransferOrder</fullName>
                <label>Avalara - InventoryTransferOrder</label>
            </value>
            <value>
                <fullName>InventoryTransferInvoice</fullName>
                <label>Avalara - InventoryTransferInvoice</label>
            </value>
            <value>
                <fullName>QUOTATION</fullName>
                <label>Vertex - Quotation</label>
            </value>
            <value>
                <fullName>INVOICE</fullName>
                <label>Vertex - Invoice</label>
            </value>
            <value>
                <fullName>DISTRIBUTE_TAX</fullName>
                <label>Vertex - Distribute Tax</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Impl_Class__c.field-meta.xml
<CustomField>
    <fullName>Impl_Class__c</fullName>
    <label>Impl Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Product_Tax_Exemption__c.field-meta.xml
<CustomField>
    <fullName>Product_Tax_Exemption__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates whether there can be product(s) which are tax exempted</description>
    <label>Product Tax Exemption?</label>
    <type>Checkbox</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Request_Template__c.field-meta.xml
<CustomField>
    <fullName>Request_Template__c</fullName>
    <label>Request Template</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Shipping_Items_Taxable__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Items_Taxable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipping Items Taxable?</label>
    <type>Checkbox</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Taxation_Policy__c.field-meta.xml
<CustomField>
    <fullName>Taxation_Policy__c</fullName>
    <label>Taxation Policy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net</fullName>
                <default>true</default>
                <label>Net</label>
            </value>
            <value>
                <fullName>Gross</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CreateTransaction</fullName>
                <default>true</default>
                <label>Avalara - CreateTransaction</label>
            </value>
            <value>
                <fullName>AdjustTransaction</fullName>
                <label>Avalara - AdjustTransaction</label>
            </value>
            <value>
                <fullName>CommitTransaction</fullName>
                <label>Avalara - CommitTransaction</label>
            </value>
            <value>
                <fullName>RefundTransaction</fullName>
                <label>Avalara - RefundTransaction</label>
            </value>
            <value>
                <fullName>SALE</fullName>
                <label>Vertex - Sale</label>
            </value>
            <value>
                <fullName>Rental</fullName>
                <label>Vertex - Rental</label>
            </value>
            <value>
                <fullName>Lease</fullName>
                <label>Vertex - Lease</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/WebStore/fields/Tax_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Document_Type__c</fullName>
    <label>Tax Document Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/WebStore/fields/Tax_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Transaction_Type__c</fullName>
    <label>Tax Transaction Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/classes/TaxConfiguration_Test.cls
@isTest
public class TaxConfiguration_Test {
     @testSetup
    static void setup() {
        WebStore webStore = new WebStore(
            Name = 'Training',
            Tax_Document_Type__c ='INVOICE',
            Tax_Transaction_Type__c ='SALE'
        );
        insert webStore;
         }

  @isTest
    static void testgetMetaDataDTO(){
       WebStore webStore = [SELECT Id FROM WebStore WHERE Name = 'Training' LIMIT 1];
        String name = 'Training';
        Tax_Provider__mdt taxMeta = getCustomMetadataRecord(name);
        Test.startTest();
        TaxMetaData result = TaxConfiguration.getMetaDataDTO(webStore.Id, null, null);
         System.assert(result != null);
        Test.stopTest();
    }
    @isTest
    static void testgetMetaDataObject(){
        Test.startTest();
        Tax_Provider__mdt metaProviderData = TaxConfiguration.getMetaDataObject();
        System.assert(metaProviderData == null);
        Test.stopTest();
    }
     public static Tax_Provider__mdt getCustomMetadataRecord(String myName) {
        Tax_Provider__mdt testTaxProvider = new Tax_Provider__mdt(
            Context_Name__c = myName,
            Context_Locale__c = 'en_GB',
            Taxation_Policy__c = 'Standard',
            Customer_Code__c = 'Cust123',
            Company_Code__c = 'Comp456',
            Shipping_Items_Taxable__c = true,
            Default_Shipping_Tax_Code__c = 'ShippingTax',
            Default_Product_Tax_Code__c = 'ProductTax',
            Consider_product_tax_codes__c = true,
            Product_Tax_Exemption__c = false,
            Customer_Tax_Exemption__c = true,
            Document_Type__c = 'INVOICE',
            Transaction_Type__c = 'SALE',
            Commit__c = true,
            Address_Line1__c = '123 Test St',
            Address_Line2__c = 'Suite 100',
            City__c = 'Test City',
            State__c = 'Test State',
            Zip_Code__c = '12345',
            Country_Code__c = 'USA',
            Impl_Class__c = 'VertexTaxProvider',
            Request_Template__c = '{"request": "template"}'
      			); 
        	return testTaxProvider;
    }
    
}