extensions/tax/vertex/objects/Product2/fields/Tax_Class_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Class_Id__c</fullName>
    <label>Tax Class Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Product2/fields/Taxable__c.field-meta.xml
<CustomField>
    <fullName>Taxable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Taxable?</label>
    <type>Checkbox</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/Tax_Provider__mdt.object-meta.xml
<CustomObject>
    <label>Tax Provider</label>
    <pluralLabel>Tax Providers</pluralLabel>
</CustomObject>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <label>Address Line1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Address_Line2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line2__c</fullName>
    <label>Address Line2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Commit__c.field-meta.xml
<CustomField>
    <fullName>Commit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Commit?</label>
    <type>Checkbox</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Consider_product_tax_codes__c.field-meta.xml
<CustomField>
    <fullName>Consider_product_tax_codes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates whether sending product tax code to the tax provider service or not. If it is set to true make sure every product has a tax code configured otherwise default product tax code will be used.</description>
    <inlineHelpText>This flag indicates whether sending product tax code to the tax provider service or not. If it is set to true make sure every product has a tax code configured otherwise default product tax code will be used.</inlineHelpText>
    <label>Consider product tax codes?</label>
    <type>Checkbox</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Context_Name__c.field-meta.xml
<CustomField>
    <fullName>Context_Name__c</fullName>
    <label>Context Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Customer_Tax_Exemption__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tax_Exemption__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates whether there can be customers who are eligible for tax exemption, if yes then customer needs to provide exemption code &amp; entity use code.</description>
    <label>Customer Tax Exemption?</label>
    <type>Checkbox</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Default_Product_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Default_Product_Tax_Code__c</fullName>
    <description>This field stores default product tax code and it is used when tax codes are sent to a tax calculator provider but a product doesn&apos;t have any  tax code configured.</description>
    <inlineHelpText>This field stores default product tax code and it is used when tax codes are sent to a tax calculator provider but a product doesn&apos;t have any  tax code configured.</inlineHelpText>
    <label>Default Product Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Default_Shipping_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Default_Shipping_Tax_Code__c</fullName>
    <label>Default Shipping Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SalesOrder</fullName>
                <default>true</default>
                <label>Avalara - SalesOrder</label>
            </value>
            <value>
                <fullName>SalesInvoice</fullName>
                <label>Avalara - SalesInvoice</label>
            </value>
            <value>
                <fullName>PurchaseOrder</fullName>
                <label>Avalara - PurchaseOrder</label>
            </value>
            <value>
                <fullName>PurchaseInvoice</fullName>
                <label>Avalara - PurchaseInvoice</label>
            </value>
            <value>
                <fullName>Avalara - ReturnOrder</fullName>
            </value>
            <value>
                <fullName>Avalara - ReturnInvoice</fullName>
            </value>
            <value>
                <fullName>InventoryTransferOrder</fullName>
                <label>Avalara - InventoryTransferOrder</label>
            </value>
            <value>
                <fullName>InventoryTransferInvoice</fullName>
                <label>Avalara - InventoryTransferInvoice</label>
            </value>
            <value>
                <fullName>QUOTATION</fullName>
                <label>Vertex - Quotation</label>
            </value>
            <value>
                <fullName>INVOICE</fullName>
                <label>Vertex - Invoice</label>
            </value>
            <value>
                <fullName>DISTRIBUTE_TAX</fullName>
                <label>Vertex - Distribute Tax</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Impl_Class__c.field-meta.xml
<CustomField>
    <fullName>Impl_Class__c</fullName>
    <label>Impl Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Product_Tax_Exemption__c.field-meta.xml
<CustomField>
    <fullName>Product_Tax_Exemption__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates whether there can be product(s) which are tax exempted</description>
    <label>Product Tax Exemption?</label>
    <type>Checkbox</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Request_Template__c.field-meta.xml
<CustomField>
    <fullName>Request_Template__c</fullName>
    <label>Request Template</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Shipping_Items_Taxable__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Items_Taxable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipping Items Taxable?</label>
    <type>Checkbox</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/objects/Tax_Provider__mdt/fields/Taxation_Policy__c.field-meta.xml
<CustomField>
    <fullName>Taxation_Policy__c</fullName>
    <label>Taxation Policy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net</fullName>
                <default>true</default>
                <label>Net</label>
            </value>
            <value>
                <fullName>Gross</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/tax/vertex/objects/Tax_Provider__mdt/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CreateTransaction</fullName>
                <default>true</default>
                <label>Avalara - CreateTransaction</label>
            </value>
            <value>
                <fullName>AdjustTransaction</fullName>
                <label>Avalara - AdjustTransaction</label>
            </value>
            <value>
                <fullName>CommitTransaction</fullName>
                <label>Avalara - CommitTransaction</label>
            </value>
            <value>
                <fullName>RefundTransaction</fullName>
                <label>Avalara - RefundTransaction</label>
            </value>
            <value>
                <fullName>SALE</fullName>
                <label>Vertex - Sale</label>
            </value>
            <value>
                <fullName>Rental</fullName>
                <label>Vertex - Rental</label>
            </value>
            <value>
                <fullName>Lease</fullName>
                <label>Vertex - Lease</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

extensions/shipping/UPS Shipping/objects/Tax_Provider__mdt/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/vertex/objects/WebStore/fields/Tax_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Document_Type__c</fullName>
    <label>Tax Document Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/WebStore/fields/Tax_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Transaction_Type__c</fullName>
    <label>Tax Transaction Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

extensions/tax/avalara/classes/TaxCartCalculatorExtensionTest.cls
@IsTest
public class TaxCartCalculatorExtensionTest {
     @testSetup static void setup() {
        Account account = new Account(Name='TestAccount');
        insert account;
        WebStore webStore = new WebStore(Name='Training', SupportedLanguages='en_US', DefaultLanguage='en_US',  Tax_Document_Type__c ='INVOICE',Tax_Transaction_Type__c ='SALE');
        insert webStore;
        WebCart cart = new WebCart(Name='Cart', WebStoreId=webStore.Id, AccountId=account.Id);
        insert cart;
        CartDeliveryGroup cartDeliveryGroup = new CartDeliveryGroup(CartId=cart.Id, Name='Default Delivery');
        insert cartDeliveryGroup;
        CartItem cartItem = new CartItem(
            CartId=cart.Id,
            Sku='SKU_Test1',
            Quantity=3.0,
            Type='Product',
            Name='TestProduct',
            CartDeliveryGroupId=cartDeliveryGroup.Id
        );
        insert cartItem;
    }
    
    @isTest
    static void testCalculate(){
        CartExtension.Cart cart = arrangeCart();
        String name = 'Training';
        Tax_Provider__mdt taxProvider = getCustomMetadataRecord(name);
        CartExtension.BuyerActionsMock buyerActions = getBuyerActionsForDeleteFromCart(cart);
        CartExtension.BuyerActionDetails buyerActionDetails = getBuyerActionDetailsForQuantityIncrease(cart.getCartItems().get(0));
        CartExtension.OptionalBuyerActionDetails optionalBuyerActionDetails = CartExtension.OptionalBuyerActionDetails.of(buyerActionDetails);
        CartExtension.CartCalculateCalculatorRequest Cartrequest = new CartExtension.CartCalculateCalculatorRequest(cart,optionalBuyerActionDetails);
      
        Test.startTest();
        TaxCartCalculatorExtension taxCaluculate = new TaxCartCalculatorExtension();
        
        taxCaluculate.calculate(Cartrequest);
        Test.stopTest();
    }
    @isTest
    static void testcreateTaxRequest(){
        CartExtension.Cart cart = arrangeCart();
        TaxMetaData taxMetaData = getTaxMeta ();
        Test.startTest();
        TaxCartCalculatorExtension taxCaluculate = new TaxCartCalculatorExtension();
        TaxProviderRequest taxprovider = taxCaluculate.createTaxRequest(cart, taxMetaData);
        System.assertnotEquals(taxprovider,null);
        Test.stopTest();
    }
     @isTest
    static void testsetTaxInCart(){
        CartExtension.Cart cart = arrangeCart();
        TaxMetaData taxMetaData = getTaxMeta ();
        TaxProviderResponse tpResponse = getTaxProviderResponse ();
        Test.startTest();
        TaxCartCalculatorExtension taxCaluculate = new TaxCartCalculatorExtension();
        taxCaluculate.setTaxInCart(cart, taxMetaData,tpResponse);
        Test.stopTest();
    }
    
   
    private static CartExtension.Cart arrangeCart() {
        Account testAccount = new Account(Name='My Account');
        insert testAccount;

        WebStore testWebStore = new WebStore(Name='Training',Tax_Document_Type__c ='INVOICE', Tax_Transaction_Type__c ='SALE');
        insert testWebStore;

        WebCart testCart = new WebCart(Name='My Cart', WebStoreId=testWebStore.Id, AccountId=testAccount.Id);
        insert testCart;

        CartDeliveryGroup testDeliveryGroup = new CartDeliveryGroup(Name='My Delivery Group', CartId=testCart.Id,DeliverToStreet='415 Mission St',DeliverToCity='San Francisco',DeliverToCountry='United States',DeliverToPostalCode='11098',DeliverToState='Maryland');
        insert testDeliveryGroup;
         Product2 testProduct2 = new Product2(name='My Product2',Tax_Class_Id__c='Test',Taxable__c=false);
        insert(testProduct2);

         Product2 testProduct = new Product2(name='My Product35',Tax_Class_Id__c='Test',Taxable__c=true);
        insert(testProduct);
        Product2 testProduct3 = new Product2(name='My Products',Taxable__c=true);
        insert(testProduct3);

        CartItem testCartItem = new CartItem(Name='My Cart Item',Product2Id=testProduct.Id,Type ='Charge', CartId=testCart.Id, CartDeliveryGroupId=testDeliveryGroup.Id);
        insert testCartItem;
        CartItem testCartItemed = new CartItem(Name='My Cart Item',Product2Id=testProduct3.Id,Type ='Charge', CartId=testCart.Id, CartDeliveryGroupId=testDeliveryGroup.Id);
        insert testCartItemed;
        CartItem testCartItem2 = new CartItem(Name='My Cart Item 2',Product2Id=testProduct2.Id, Type ='Product',CartId=testCart.Id, CartDeliveryGroupId=testDeliveryGroup.Id);
        insert testCartItem2;
        CartItem testCartItem3 = new CartItem(Name='My Cart Item 2',Product2Id=testProduct.Id, Type ='Product',CartId=testCart.Id, CartDeliveryGroupId=testDeliveryGroup.Id);
        insert testCartItem3;
         CartItem testCartItem4 = new CartItem(Name='My Cart Item 2',Product2Id=testProduct3.Id, Type ='Product',CartId=testCart.Id, CartDeliveryGroupId=testDeliveryGroup.Id);
        insert testCartItem4;
        CartTax cartTax = new CartTax( CartItemId=testCartItem.Id, Name='CartTax', Amount=20.00,TaxType='Actual',TaxCalculationDate=date.newInstance(2023, 10, 21) );
        insert cartTax;
        CartValidationOutput cartValidate = new CartValidationOutput(Name='cartValidate', Type = 'Taxes',CartId=testCart.Id, Level = 'Info',RelatedEntityId = testCartItem.Id);
        insert cartValidate;
       Promotion promotion = new Promotion(Name ='Promotion', IsActive =true, IsCommercePromotion = true,IsAutomatic= false);
        insert promotion;
        CartItemPriceAdjustment cartItemAdj = new CartItemPriceAdjustment(PriceAdjustmentCauseId=promotion.id,  CartId=testCart.Id,CartItemId=testCartItem.Id,Name ='cartItemAdj',TotalAmount=45.00, AdjustmentSource ='Rule', AdjustmentType ='AdjustmentPercentage', AdjustmentValue =90.00, AdjustmentTargetType='Cart');
        insert cartItemAdj;
        WebCartAdjustmentBasis testCartAdjustmentBasis = new WebCartAdjustmentBasis(Name='My Coupon', WebCartId=testCart.Id);
        insert testCartAdjustmentBasis;

        return CartExtension.CartTestUtil.getCart(testCart.Id);
    }
    private static TaxMetaData getTaxMeta (){
        TaxMetaData taxMetaData = new TaxMetaData();
        taxMetaData.shippingItemsTaxable = false;
        taxMetaData.useProductTaxCodes =true;
        taxMetaData.productTaxExemption = true;
        taxMetaData.defaultProductTaxCode ='Testing';
        taxMetaData.defaultShippingTaxCode='TestShip';
        return taxMetaData;
    }
    private static TaxProviderResponse getTaxProviderResponse (){
        TaxProviderResponse taxProviderResponse = new TaxProviderResponse();
        Map<String, TaxableCartItem> taxableMap = new Map<String, TaxableCartItem>();
        List<LineItemTaxDetails> lineItemTexasList = new List<LineItemTaxDetails>();
        taxProviderResponse.taxableCartItems = taxableMap;
        TaxableCartItem taxableCartItem = new TaxableCartItem();
        taxableMap.put(taxableCartItem.id,taxableCartItem);
        taxableCartItem.amount = 100.00;
        taxableCartItem.quantity = 1;
        taxableCartItem.sku = 'ABC';
        taxableCartItem.lineItemType = 'Product';
        taxableCartItem.taxClassId = 'Taxable';
        taxableCartItem.productExemptionCode = 'None';
        taxableCartItem.entityUseCode = 'None';
        taxableCartItem.street = '123 Main St';
        taxableCartItem.city = 'Anytown';
        taxableCartItem.state = 'CA';
        taxableCartItem.postalCode = '12345';
        taxableCartItem.country = 'US';
        taxableCartItem.lineItemTexas = lineItemTexasList;
        LineItemTaxDetails lineItemTaxDetails = new LineItemTaxDetails();
        lineItemTaxDetails.rate = 0.0825;
        lineItemTaxDetails.tax = 8.25;
        lineItemTaxDetails.taxName = 'California State Tax';
        lineItemTaxDetails.taxType = 'SalesTax';
        lineItemTexasList.add(lineItemTaxDetails);
        return taxProviderResponse;
    }
    private static CartExtension.BuyerActionsMock getBuyerActionsForDeleteFromCart(CartExtension.Cart cart) {
        return getCartItemChangedBuyerActions(cart);
    }
    private static CartExtension.BuyerActionDetails getBuyerActionDetailsForQuantityIncrease(CartExtension.CartItem cartItemWithIncreasedQuantity) {
        CartExtension.CartItemChange cartItemChange = new CartExtension.CartItemChange.Builder()
                                                            .withChangedItem(CartExtension.OptionalCartItem.of(cartItemWithIncreasedQuantity))
                                                            .withQuantityIncreased(True)
                                                            .build();
        List<CartExtension.CartItemChange> changedCartItems = new List<CartExtension.CartItemChange>{cartItemChange};
        CartExtension.BuyerActionDetails buyerActionDetails = new CartExtension.BuyerActionDetails.Builder()
                                                                                      .withCartItemChanges(changedCartItems)
                                                                                      .build();
        return buyerActionDetails;
    }
    private static CartExtension.BuyerActionsMock getCartItemChangedBuyerActions(CartExtension.Cart cart) {
        CartExtension.BuyerActionsMock buyerActions = new CartExtension.BuyerActionsMock(cart);
        buyerActions.setCartItemChanged(True);
        return buyerActions;
    }
    public static Tax_Provider__mdt getCustomMetadataRecord(String myName) {
         Tax_Provider__mdt testTaxProvider = new Tax_Provider__mdt(
            Context_Name__c = myName,
            Context_Locale__c = 'en_GB',
            Taxation_Policy__c = 'Standard',
            Customer_Code__c = 'Cust123',
            Company_Code__c = 'Comp456',
            Shipping_Items_Taxable__c = true,
            Default_Shipping_Tax_Code__c = 'ShippingTax',
            Default_Product_Tax_Code__c = 'ProductTax',
            Consider_product_tax_codes__c = true,
            Product_Tax_Exemption__c = false,
            Customer_Tax_Exemption__c = true,
            Document_Type__c = 'INVOICE',
            Transaction_Type__c = 'SALE',
            Commit__c = true,
            Address_Line1__c = '123 Test St',
            Address_Line2__c = 'Suite 100',
            City__c = 'Test City',
            State__c = 'Test State',
            Zip_Code__c = '12345',
            Country_Code__c = 'USA',
            Impl_Class__c = 'TestImplClass',
            Request_Template__c = '{"request": "template"}'
      			); 
        return testTaxProvider;
    }
    private static TaxProviderRequest  taxProviderRequest(){
        WebCart webCart = [SELECT Id FROM WebCart WHERE Name = 'Cart' LIMIT 1];
        TaxProviderRequest taxProvider = new TaxProviderRequest();
         TaxMetaData taxmeta = new TaxMetaData();
        taxProvider.street ='1600 Massachusetts Avenue';
        taxProvider.city = 'Washington';
        taxProvider.state = 'Washington DC';
        taxProvider.postalCode = '20011';
        taxProvider.country = 'United States';
        taxProvider.cartId = webCart.id;
        taxProvider.hasMultipleShipments = true;
        taxProvider.taxMetaData = taxmeta;
        taxProvider.getData('Test');
        taxProvider.addData('Test', webCart);
        Tax_Provider__mdt testTaxProvider =[Select id from Tax_Provider__mdt where Impl_Class__c = 'TestImplClass' LIMIT 1];
        taxmeta.id = testTaxProvider.Id;
        taxmeta.endPoint ='https://api.test.com/endpoint';
        taxmeta.httpMethod = 'POST';
        taxmeta.serviceTimeout ='30';
        taxmeta.requestJSON='{"key": "value"}';
        taxmeta.providerImplClass ='TestProviderClass';
        taxmeta.mockedResponse ='{"response": "mocked"}';
        taxmeta.serviceImplClass ='TestServiceClass';
        taxmeta.addMetaData('key2', 100);
        taxmeta.serviceMode ='Test';
        taxmeta.getMetaData('Test');
        taxmeta.namedCredentials= 'TestCredentials';
        return taxProvider;
    }
    private static void assertNoCartValidationOutputs(CartExtension.Cart cart) {
        String errorString = '';
        Iterator<CartExtension.CartValidationOutput> cvoIterator = cart.getCartValidationOutputs()
            .iterator();
        while (cvoIterator.hasNext()) {
            errorString += cvoIterator.next().getMessage() + '; ';
        }
    }
     
}