extensions/shipping/UPS Shipping/objects/Internal_Shipping_Rate__mdt/Internal_Shipping_Rate__mdt.object-meta.xml
<CustomObject>
    <label>Internal Shipping Rate</label>
    <pluralLabel>Internal Shipping Rates</pluralLabel>
</CustomObject>

extensions/shipping/FedEx Shipping/objects/Internal_Shipping_Rate__mdt/fields/Cart_Max_Price__c.field-meta.xml
<CustomField>
    <fullName>Cart_Max_Price__c</fullName>
    <label>Cart Max Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Internal_Shipping_Rate__mdt/fields/Cart_Max_Weight__c.field-meta.xml
<CustomField>
    <fullName>Cart_Max_Weight__c</fullName>
    <label>Cart Max Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Internal_Shipping_Rate__mdt/fields/Cart_Min_Price__c.field-meta.xml
<CustomField>
    <fullName>Cart_Min_Price__c</fullName>
    <label>Cart Min Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Internal_Shipping_Rate__mdt/fields/Cart_Min_Weight__c.field-meta.xml
<CustomField>
    <fullName>Cart_Min_Weight__c</fullName>
    <label>Cart Min Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Internal_Shipping_Rate__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

extensions/shipping/FedEx Shipping/objects/Internal_Shipping_Rate__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Internal_Shipping_Rate__mdt/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

extensions/shipping/UPS Shipping/objects/Internal_Shipping_Rate__mdt/fields/Shipping_Provider__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Provider__c</fullName>
    <label>Shipping Provider</label>
    <referenceTo>Shipping_Provider__mdt</referenceTo>
    <relationshipLabel>Internal Shipping Rates</relationshipLabel>
    <relationshipName>Internal_Shipping_Rates</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

extensions/shipping/UPS Shipping/classes/InternalShippingProvider.cls
public class InternalShippingProvider extends ShippingProvider {
  public InternalShippingProvider() {
  }
  public override Map<String, ShippingProviderResponse> retrieveShippingRates(
    ShippingProviderRequest shippingRequest
  ) {
    List<String> responseList = new List<String>();
    Map<String, ShippingProviderResponse> shippingMethodsWithRate = new Map<String, ShippingProviderResponse>();
    Decimal totalCartWeight = 0;
    try {
      List<Decimal> lstShippingWeight = calculateCartWeight(shippingRequest);
      for (Decimal weight : lstShippingWeight) {
        totalCartWeight += weight;
      }
      shippingRequest.packageWeight = totalCartWeight;
      shippingMethodsWithRate = getShippingOptionsFromResponse(
        responseList,
        shippingRequest
      );
    } catch (Exception expObj) {
      System.debug(
        'Exception due to error ====' +
          expObj.getMessage() +
          'at Line Number ====' +
          expObj.getLineNumber()
      );
      // WK_Exception.log(expObj, applicationName, moduleName, className,
      // methodName, supportData);
    }
    return shippingMethodsWithRate;
  }

  public override Map<String, ShippingProviderResponse> getShippingOptionsFromResponse(
    List<String> responseList,
    ShippingProviderRequest shippingRequest
  ) {
    Map<String, ShippingProviderResponse> shippingMethodsWithRate = new Map<String, ShippingProviderResponse>();
    List<Internal_Shipping_Rate__mdt> shippingRates = [
      SELECT
        Id,
        Name__c,
        Rate__c,
        Cart_Max_Price__c,
        Cart_Max_Weight__c,
        Cart_Min_Price__c,
        Cart_Min_Weight__c,
        Shipping_Provider__c
      FROM Internal_Shipping_Rate__mdt
      WHERE Shipping_Provider__c = :shippingRequest.shippingMetaData.id AND Is_Active__c = true 
    ];
    ShippingProviderResponse shippingResponse;
    if (shippingRates != null && shippingRates.size() > 0) {
      for (Internal_Shipping_Rate__mdt rate : shippingRates) {
        shippingResponse = new ShippingProviderResponse();
        shippingResponse.serviceCode = rate.Name__c;
        shippingResponse.cost = rate.Rate__c;
        shippingResponse.carrier = shippingRequest.shippingMetaData.carrier;
        shippingResponse.displayOrder = shippingRequest.shippingMetaData.displayOrder;
        shippingMethodsWithRate.put(
          shippingResponse.serviceCode,
          shippingResponse
        );
      }
    }
    return shippingMethodsWithRate;
  }
  public override void prepareRequestBody(
    ShippingProviderRequest shippingRequest,
    Map<String, String> callOutRequest
  ) {
  }
}